Add functions to update balances for SLP tokens
new-order-network/dao-app-frontend pull request #55
Opened 2022-01-24 08:58 UTC by arjanvillon

# Project: New Order DAO App Frontend

## Motivation and Context

Why is this change required? What problem does it solve?
- Balances doesn't update real-time after depositing / withdrawing which makes the users confused on whether they have already deposited
- Users need to refresh just to see these updates

## Description

Describe your changes in detail.
- Call the necessary functions to get the latest balance after a transaction is done
- Most of the `NEWO` balances are already updating but `SLP` doesn't

### Related Issues

Resolves #49 

### How Has This Been Tested?

Please describe in detail how you tested your changes.
- Tried to stake, deposit and withdraw. Updated real-time ✅ 

### Screenshots/Video (if appropriate):

If this PR covers a UI or workflow change, an image displaying the change should accompany the PR
  

## Types of changes

What types of changes does your code introduce? Put an `x` in all the boxes that apply:
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

Go over all the following points, and put an `x` in all the boxes that apply. If you're unsure about any of these, don't hesitate to ask. We're here to help!
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have updated the CHANGELOG file accordingly for the version that this merge modifies.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-01-25 18:54 UTC, justingreenberg requested changes
overall LGTM, just a few minor nits

2022-01-25 18:54 UTC, justingreenberg commented on src/pages/InvestPage/components/ActiveDepositsTab/components/Deposits/Deposits.tsx
>        if (address) {
we can remove this conditional block now

2022-01-25 18:54 UTC, justingreenberg commented on src/pages/InvestPage/components/ActiveDepositsTab/components/Deposits/Deposits.tsx
>        if (address) {
this block can also be removed

2022-01-25 18:54 UTC, justingreenberg commented on src/pages/InvestPage/components/ActiveDepositsTab/components/Deposits/Deposits.tsx
> +        await getSlpRewards(address);
same as above...

```ts
if (address)
  await Promise.all([
    getSlpRewards(address),
    getUserSlpBalance(address),
  ])
```

applies to a few other areas as well

2022-01-25 18:54 UTC, justingreenberg commented on src/pages/InvestPage/components/ActiveDepositsTab/components/Deposits/Deposits.tsx
> +    const rewardAmount = await slpVaultClient.getRewards(who);
since there's no waterfall dependencies i think these could also be made in parallel eg.

```ts
const [balance, rewardAmount] = await Promise.all([
  slpVaultClient.getUserVaultBalance(who),
  slpVaultClient.getRewards(who),
])
```

2022-01-25 18:54 UTC, justingreenberg commented on src/pages/InvestPage/components/DepositInfo/DepositInfo.tsx
can be parallelized


```ts
await Promise.all([
  getSlpVaultBalance(),
  getUserSlpVaultBalance(),
  getSlpTokenBalance(),
])
```

2022-01-26 07:50 UTC, arjanvillon commented on src/pages/InvestPage/components/ActiveDepositsTab/components/Deposits/Deposits.tsx
> +    const rewardAmount = await slpVaultClient.getRewards(who);
oh wow never heard of this concept before. pretty neat. thanks @justingreenberg

2022-01-26 07:59 UTC, arjanvillon commented
Just pushed a code refactor update with your suggestions @justingreenberg. Thank you. Really appreciate it.

2022-01-26 08:01 UTC, brokenomics commented on src/pages/InvestPage/components/ActiveDepositsTab/components/Deposits/Deposits.tsx
> +    const rewardAmount = await slpVaultClient.getRewards(who);
await is just syntactic sugar for a Promise! Definitely a good idea to group consecutive awaits where possible

2022-01-26 08:24 UTC, brokenomics approved these changes
Looks like Justin's feedback is all applied, gonna go ahead and stamp!

2022-01-26 17:47 UTC, justingreenberg approved these changes

2022-01-26 17:59 UTC, merged